version: "2.0"

services:
  db:
    image: mysql:5.7
    container_name: brydge-cashout-api
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
